### ISSUE TITLE
Nové elementy do XML

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/tool#1]
Pro maďarsko je zapotřebí posílat u dobropisů číslo původního dokladu (faktury) a rozlišovat zda je to dobropis na celou částku nebo jen část.  Takže potřebuji dva nové elementy:
1) číslo faktury na kterou je dobropis vystaven
2) původní částka faktury (na základě rozdílu pak řeknu, zda je na celou částku nebo nikoliv) - případně jen příznak pokud to uznáš jako vhodnější řešení

V db na to pole nejsou, takže i vytvoření příslušných sloupců.

**Comment by jzelenka** [comment]
na Fakture existuje parent_invoice_id, kam se ma u dobpropisu vyplnovat cislo puvodni faktury.
Ale koukam ze to neni nikde vyplnene, takze @milant007 to musi doplnit

Udelal jsem opravu, ktera, u faktur ktere to maji vyplnene, vyplivne element `<parentInvoice>`  kam jsem dal par cen:

      <itemPrice>18.15000000</itemPrice>
      <itemPriceLcy>499.13000000</itemPriceLcy>
    </items>
    <parentInvoice>
      <invoiceNumber>OPTI 20160031</invoiceNumber>
      <totalPrice>36.00000000</totalPrice>
      <totalPriceLcy>36.00000000</totalPriceLcy>
      <totalAdjustedPrice>36.00000000</totalAdjustedPrice>
      <totalAdjustedPriceLcy>36.00000000</totalAdjustedPriceLcy>
    </parentInvoice>
  </invoice>
