### ISSUE TITLE
Invoice_invoiceDirectionEQUALISSUED v TXT

### ISSUE THREAD

**Issue by krivohlavek** [zauzoo/tool#2]
Když dělám exportní soubory do Scaly, tak to na začátek souboru hází "Invoice_invoiceDirectionEQUALISSUED", dělám někde chybu?

Dřív to nedělalo - před několika měsící jsem dělal export pro CZ a tam to bylo v poho. Jenže CZ to zatím nepoužívá a RO má podobné exporty, tak jsem je teď použil a zjistil to. nenapadá Tě něco?

**Comment by jzelenka** [comment]
DO XML jsem pred nejakou dobou pridal parametry gridu - abyste meli k dispozici napriklad za jake obdobi. Myslim ze to bylo potreba pro HU Legal.

Takze kdyz se podivas na to vstupni XML  pro transformaci (Export /  XML Object) tak uvidis:

    <filters>
        <column>Invoice_invoiceDirection</column>
        <operator>EQUAL</operator>
        <stringValues>ISSUED</stringValues>
    </filters>

Takze to nejakym omylem v te transformaci kopirujes na vystup....

zaviram.
